version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'type:chore'
    commit-message:
      prefix: 'chore'
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'type:chore'
    commit-message:
      prefix: 'chore'
    groups:
      angular:
        patterns:
          - '@angular/*'
      typescript:
        patterns:
          - 'typescript'
          - 'typescript-eslint'
