name: Bug
description: Relatório de bug
title: "[Bug] "
labels: ["type:bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: O que está acontecendo de errado?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Passos detalhados para reproduzir o bug
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
      description: O que deveria acontecer?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Comportamento atual
      description: O que está acontecendo?
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Ambiente
      description: "Informações sobre o ambiente (OS, versão, hardware)"
  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      options:
        - Low
        - Normal
        - High
        - Critical
    validations:
      required: true
